{
 "title": "BORG",
 "description": "borg backup",
 "tags": [
  "borg",
  "system"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "repo",
    "query": {
     "query": "label_values(borg_archives_count,repo)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Time since last backup",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-borg_last_archive_timestamp{repo=~\"$node.*\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Archives count",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_archives_count{repo=~\"$node.*\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Files count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "borg_files_count{repo=~\"$node.*\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Total size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "borg_total_size{repo=~\"$node.*\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Total size dedup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "borg_total_size_dedup{repo=~\"$node.*\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Last size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "borg_last_size{repo=~\"$node.*\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Last size dedup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "borg_last_size_dedup{repo=~\"$node.*\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  }
 ]
}